# Generated by Django 5.0.2 on 2024-02-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencia', models.IntegerField(unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_pago', to='ventasistema.ordenventa')),
            ],
        ),
    ]
